---

- name: Take backup
  hosts: S3
  connection: local
  gather_facts: false
  vars_files:
    - /home/patryk/Arista_Ansible/credentials.yaml
#.credentials.yaml - if it's in the same location



  tasks:
  - name: INPUT SHOW COMMAND TO DEVICES
    eos_command:
      commands: "{{ SHOW_COMMAND }}"
      provider: # How you gonna connect to your device:
        host: "{{ inventory_hostname }}"
        username: "{{ USERNAME }}"
        password: "{{ DEVICE_PASSWORD }}"
        use_ssl: no
        authorize: yes
        #transport: cli
    register: print_output

  - name: OUTPUT SHOW RUN to SCREEN
    debug:
      msg: "{{ print_output.stdout_lines }}"

  - name: OUTPUT SHOW COMMAND to FILE
    copy: content="{{ print_output.stdout[0] }}" dest="./backup_output/{{ inventory_hostname }}.bak"
